name: opentyrian
version: 'trunk'
icon: icons/opentyrian.png
summary: An arcade-style shoot 'em up
description: |
  OpenTyrian is a port of the DOS shoot-em-up Tyrian.

  Tyrian is an arcade-style vertical scrolling shooter. The story is set in
  20,031 where you play as Trent Hawkins, a skilled fighter-pilot employed to
  fight Microsol and save the galaxy.

grade: stable
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  opentyrian:
    command: tyrian-launch
    plugs:
      - joystick
      - network
      - network-bind
      - opengl
      - pulseaudio
      - x11

parts:
  launcher:
    source: scripts
    plugin: dump
    install: |
      chmod +x tyrian-launch
    organize:
      tyrian-launch: bin/tyrian-launch

  icon:
    source: icons
    plugin: dump
    organize:
      opentyrian.png: usr/local/share/icons/opentyrian.png

  tyrian:
    source: https://bitbucket.org/opentyrian/opentyrian
    source-type: hg
    plugin: make
    build-packages:
      - libsdl-net1.2-dev
      - libsdl1.2-dev
    stage-packages:
      - curl
      - libsdl-net1.2
      - libsdl1.2debian
      - unzip
    prime:
      - bin/tyrian-launch
      - usr/bin/curl
      - usr/bin/unzip
      - usr/lib
      - usr/local/bin
      - usr/local/share/icons/opentyrian.png
